import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import "./grid.scss";


const Grid: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>Grid without media queries </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
      <div className="card">
            <div className="info">
                <strong className="title">My Title</strong>
                <p className="desc">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia consectetur sapiente ipsam nihil velit quae ab unde quasi exercitationem esse</p>        
            </div>
            <img src="http://freeaussiestock.com/free/Victoria/Melbourne/slides/fed_square.jpg"/>
        </div>
        <div className="card">
            <div className="info">
                <strong className="title">My Title</strong>
                <p className="desc">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia consectetur sapiente ipsam nihil velit quae ab unde quasi exercitationem esse</p>        
            </div>
            <img src="https://media.defense.gov/2013/Jul/16/2000032379/-1/-1/0/130628-F-DQ639-002.JPG"/>
        </div>
        <div className="card">
            <div className="info">
                <strong className="title">My Title</strong>
                <p className="desc">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia consectetur sapiente ipsam nihil velit quae ab unde quasi exercitationem esse</p>        
            </div>
            <img src="https://s0.geograph.org.uk/geophotos/03/25/64/3256477_ec7d83ab.jpg"/>
        </div>
        <div className="card">
            <div className="info">
                <strong className="title">My Title</strong>
                <p className="desc">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia consectetur sapiente ipsam nihil velit quae ab unde quasi exercitationem esse</p>        
            </div>
            <img src="http://freeaussiestock.com/free/Victoria/Melbourne/slides/melbourne_museum_roof.jpg"/>
        </div>
        <div className="card">
            <div className="info">
                <strong className="title">My Title</strong>
                <p className="desc">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia consectetur sapiente ipsam nihil velit quae ab unde quasi exercitationem esse</p>        
            </div>
            <img src="https://live.staticflickr.com/2387/1726578675_62f09cb233_z.jpg"/>
        </div>
        <div className="card">
            <div className="info">
                <strong className="title">My Title</strong>
                <p className="desc">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia consectetur sapiente ipsam nihil velit quae ab unde quasi exercitationem esse</p>        
            </div>
            <img src="https://s0.geograph.org.uk/geophotos/04/31/24/4312454_79d0a1d8.jpg"/>
        </div>
      </main>

      <footer className="footer">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className="logo">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Grid;
