import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import { GetStaticProps } from "next";
import {axiosGetJsonData} from "../../utils/utilFunctions";
import PokemonItemModified from "../../components/PokemonItemModified/PokemonItemModified";

export interface fetchedPokemons {
  results: {
    url: string;
    name: string;
  }[];
}

const Home: NextPage<fetchedPokemons> = ({ results }) => {
  // const randomPokemonNumber = Math.floor(Math.random() * 152);
  let pokemons = results
    // .slice(randomPokemonNumber - 5, randomPokemonNumber + 5)
    .map((pokemon) => {
      return (
        <PokemonItemModified url={pokemon.url} name={pokemon.name} key={pokemon.url} />
      );
    });
  return (
    <div className={styles.container}>
      <Head>
        <title>Kanto Pokedex </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>All Kanto Pokemon</h1>
        <div className={styles.pokemonContainer}>{pokemons}</div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  const res = await axiosGetJsonData<fetchedPokemons>(
    "https://pokeapi.co/api/v2/pokemon?limit=151"
  );
  const results = res.results;

  if (!results) {
    return {
      redirect: {
        destination: "/no-data",
        statusCode: 307
      },
    };
  }
  if (results.length === 0) {
    return {
      notFound: true
    };
  }

  return {
    props: {
      results,
    },
  };
};

export default Home;
